"""message relationship

Revision ID: a0da8efecb82
Revises: a32448f1eeea
Create Date: 2020-12-27 23:56:45.736223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0da8efecb82'
down_revision = 'a32448f1eeea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('crew_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'messages', 'crews', ['crew_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'crew_id')
    # ### end Alembic commands ###
