"""first migration

Revision ID: cb4f6d1bd164
Revises: 
Create Date: 2020-12-27 01:05:57.251494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4f6d1bd164'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('crew_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'crews', ['crew_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'crew_id')
    # ### end Alembic commands ###
